[default]
root_pass = "password"
db_pass = "secret"
jwt_hash = "longHash"
jwt_algo = "HS256"
root_user = ""
root_email = ""
root_role = "root"
db_driver = ""
db_user = ""
db_address = ""
[production]
root_pass = "password"
db_pass = "secret"
jwt_hash = "longHash"
jwt_algo = "HS256"
root_user = ""
root_email = ""
root_role = "root"
db_driver = ""
db_user = ""
db_address = ""
[development]
root_pass = "password"
db_pass = "secret"
jwt_hash = "longHash"
jwt_algo = "HS256"
root_user = ""
root_email = ""
root_role = "root"
db_driver = ""
db_user = ""
db_address = ""
[testing]
root_pass = "password"
db_pass = "secret"
jwt_hash = "longHash"
jwt_algo = "HS256"
root_user = ""
root_email = ""
root_role = "root"
db_driver = ""
db_user = ""
db_address = ""