[default]
root_senha = "biscoito"
db_pass = "segredo"
hash_1 = "3aabce021b58ee1f052484dc6787de8556d308b8"
hash_2 = "HS256"
[production]
root_senha = "biscoito"
db_pass = "segredo"
hash_1 = "3aabce021b58ee1f052484dc6787de8556d308b8"
hash_2 = "HS256"
[development]
root_senha = "biscoito"
db_pass = "segredo"
hash_1 = "3aabce021b58ee1f052484dc6787de8556d308b8"
hash_2 = "HS256"
[testing]
root_senha = "biscoito"
db_pass = "segredo"
hash_1 = "3aabce021b58ee1f052484dc6787de8556d308b8"
hash_2 = "HS256"