runtime: python39 # or another supported version

instance_class: B2

basic_scaling:
  max_instances: 1
  idle_timeout: 5m

env_variables:
  ENV_FOR_DYNACONF: "production"
  GOOGLE_APPLICATION_CREDENTIALS: "auth_gcp.json"
  PORT: "8080"


handlers:

- url: /js
  static_dir: estaticos/js

- url: /css
  static_dir: estaticos/css

entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app